# Generated by Django 5.2.13 on 2026-06-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_order_address_order_contact_order_instructions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('raw', 'Raw Makhana'), ('flavoured', 'Flavoured Makhana'), ('flour', 'Khapli Wheat Flour')], default='flavoured', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
