# Generated by Django 5.2.13 on 2026-06-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('raw', 'Raw Makhana'), ('flavoured', 'Flavoured Makhana'), ('combo', 'Makhana Combo'), ('flour', 'Khapli Wheat Flour')], default='flavoured', max_length=20),
        ),
    ]
